name:                adventure-engine
version:             0.1.0.0
github:              "agentultra/adventure-engine"
license:             BSD-3-Clause
author:              "James King"
maintainer:          "james@agentultra.com"
copyright:           "2020 James King"

extra-source-files:
- README.md
- ChangeLog.md
- LICENSE

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/agentultra/adventure-engine#readme>

dependencies:
- base >= 4.7 && < 5

default-extensions:
- LambdaCase
- OverloadedStrings

library:
  source-dirs: src
  dependencies:
  - containers
  - data-default
  - haskeline
  - lens
  - monomer
  - mtl
  - text

executables:
  adventure-engine-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - adventure-engine
    - text

tests:
  adventure-engine-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - adventure-engine
